export const ADD_POST = "ADD_POST";
export const EDIT_POST = "EDIT_POST";
export const SELECTED_POST = "SELECTED_POST";
export const SET_TO_LOCAL_STORAGE = "SET_TO_LOCAL_STORAGE";

export const GET_POSTS_START = "GET_POSTS_START";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const DELETE_SELECTED = "DELETE_SELECTED";

export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const PUT_POSTS_START = "PUT_POSTS_START";
export const PUT_POSTS_SUCCESS = "PUT_POSTS_SUCCESS";
export const PUT_POSTS_FAIL = "PUT_POSTS_FAIL";

export const DELETE_POSTS_START = "DELETE_POSTS_START";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
export const DELETE_POSTS_FAIL = "DELETE_POSTS_FAIL";

export const DELETE_SELECTED_START = "DELETE_SELECTED_START";
export const DELETE_SELECTED_SUCCESS = "DELETE_SELECTED_SUCCESS";
export const DELETE_SELECTED_FAIL = "DELETE_SELECTED_FAIL";

export const COMPLETED_POST_START = "COMPLETED_POST_START";
export const COMPLETED_POST_SUCCESS = "COMPLETED_POST_SUCCESS";
export const COMPLETED_POST_FAIL = "COMPLETED_POST_FAIL";

export const SELECTED_POST_START = "SELECTED_POST_START";
export const SELECTED_POST_SUCCESS = "SELECTED_POST_SUCCESS";
export const SELECTED_POST_FAIL = "SELECTED_POST_FAIL";
